# Generated by Django 5.2.11 on 2026-02-28 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_hydraulicsow_sow_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possale',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CREDIT', 'Charge/Credit'), ('CARD', 'Card/Digital'), ('GCASH', 'GCash'), ('BANK', 'Bank Transfer')], default='CASH', max_length=10),
        ),
    ]
