# Generated by Django 5.2.11 on 2026-03-01 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_alter_possale_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='possale',
            name='has_price_override',
            field=models.BooleanField(default=False, help_text="Flagged if any item's price was manually lowered."),
        ),
        migrations.CreateModel(
            name='PriceOverrideLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('override_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(blank=True, help_text='Reason for the price change.', max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pos_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_overrides', to='inventory.possale')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_overrides', to='inventory.product')),
                ('salesman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Price Override Log',
                'verbose_name_plural': 'Price Override Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
