# Generated by Django 5.2.11 on 2026-04-29 11:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_create_default_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundHistory',
            fields=[
            ],
            options={
                'verbose_name': 'Refund History',
                'verbose_name_plural': 'Refund History',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.stocktransaction',),
        ),
        migrations.AlterModelOptions(
            name='stocktransaction',
            options={'ordering': ['-timestamp', '-id'], 'permissions': [('can_adjust_stock', 'Can adjust stock quantities'), ('can_view_history', 'Can view product edit history'), ('can_view_reports', 'Can view and generate reports')]},
        ),
        migrations.AlterField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum allowed credit balance.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='priceoverridelog',
            name='reason',
            field=models.CharField(default='Not provided', help_text='Reason for the price change.', max_length=255),
        ),
    ]
